version: '3.9'
services:
  emacs-core:
    build: ./emacs
    container_name: emacs-core
    volumes:
      - ./data/org:/home/argosy/org
    depends_on:
      - autogen-ai
    ports:
      - "2222:22"
  
  autogen-ai:
    build: ./python
    container_name: autogen-ai
    ports:
      - "8000:8000"
